spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/testdb
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MariaDB106Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: bae9aa27df816d042ef63a7e710aba74
            client-secret: yrzPZCf5ZbeM7XogAzXaTawcaghPFtSP
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            scope: openid,profile_nickname,profile_image,account_email
        provider:
          kakao:
            issuer-uri: https://kauth.kakao.com

cloud:
  aws:
    s3:
      bucket: secret
    credentials:
      access-key: secret
      secret-key: secret
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

#logging
logging:
  level:
    community:
      whatever:
        petcoming: debug